### PR TITLE
Give player feedback on move quality

### PR DESCRIPTION
**Pull request by benknoble**
The first version (https://github.com/benknoble/limchess/pull/22/commits/89a6f8c4a004d20beea68ca3127f91777b2ddb3e) simply checks if the score is in the players favor.  When the
player makes a move which worsens the score but keeps it in the player's favor,
it will still be evaluated as "good."

The second version (https://github.com/benknoble/limchess/pull/22/commits/3b49c1081f2fdc504070b067a940368621b508a8) checks if the score *improved* in the player's favor.

### CODE REVIEW

**Comment by zlintz14** [comment]
I checked out and played around with both. I personally like the second version, which states a "good move" if the score _improves_ in the players favor - I think the other version gives the user a false sense of what a "good move" is. Do you want me to go ahead and merge since second version should be the most recent commit? Also, do you want to merge my gamepad stuff first?

**Comment by benknoble** [comment]
I’ll probably touch-up the docs a bit and then merge. Gamepad can merge when ready @zlintz14 esp. if the docs have been updated

**Comment by benknoble** [comment]
@zlintz14 take a look and merge if it's ready!

**Comment by zlintz14** [comment]
Looks good! Just wanted to confirm one thing before merging, it is reporting your move relative to if your score went up or down each move correct? Also, should we clear the good/bad move status when new game is pressed or no? Other than that looks great!

**Comment by benknoble** [comment]
@zlintz14 close enough: it reports good when the score gets better for you (more positive when white, more negative when black) and bad when the score gets worse for you (more negative when white, more positive when black).

Remember that negative scores means black is winning, while positive scores means white is winning.

This gives us the following:

```
               | White | Black |
---------------+-------+-------+
Current > Prev |  good |  bad  |
---------------+-------+-------+
Current < Prev | bad   | good  |
--------------------------------
```

**Pull request merged**
